name: CI/CD — Build & Deploy (Self-hosted)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build JAR
        run: mvn -B clean package -DskipTests

      - name: Build Docker image
        run: docker build -t todo-app:${{ github.sha }} .

      - name: Stop & remove old container (if any)
        run: |
          docker stop todo-app || true
          docker rm todo-app || true

      - name: Run new container
        run: docker run -d \
          --restart unless-stopped \
          -p 8080:8080 \
          --name todo-app \
          todo-app:${{ github.sha }}

      - name: Cleanup dangling images (optional)
        run: docker image prune -f || true
