# Start from an OpenJDK base image
FROM openjdk:21-jdk-slim

# Set a working directory inside the container
WORKDIR /app

# Copy the Maven/Gradle build artifact into the container
# Assuming your Spring Boot jar is in target/ folder
COPY target/ToDoApp-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your Spring Boot app runs on
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "app.jar"]
