spring:
  application:
    name: ToDoApp

  datasource:
    url: jdbc:postgresql://localhost:5432/DemoTesting
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



